default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['RAILS_POSTGRES_USER'] %>
  password: <%= ENV['RAILS_POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: bicicas_development

test:
  <<: *default
  database: bicicas_test

# CREATE ROLE rails PASSWORD 'railspw' CREATEDB LOGIN;