default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: lucasbraun


development:
  <<: *default
  database: bicimas_development

test:
  <<: *default
  database: bicimas_test
